
import java.awt.BorderLayout;
import java.awt.Color;
import java.util.Random;
import javax.swing.JButton;
import static javax.swing.WindowConstants.EXIT_ON_CLOSE;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Fer
 */
public class main extends javax.swing.JFrame {
    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    static int GenerateRand()
    {
        Random rand = new Random();
        return rand.nextInt(256);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        MiVentana ventana = new MiVentana();
        ventana.setLayout(new BorderLayout());
        ventana.setSize(1080, 720);
        
        MiPanelMenu menu = new MiPanelMenu();
        menu.setBackground(new Color(GenerateRand(), GenerateRand(), GenerateRand()));
        
        JButton b1, b2;
        b1 = new JButton("Pintar");
        b2 = new JButton("Dibujar");
        menu.add(b1);
        menu.add(b2);
        
        MiPanelLienzo lienzo = new MiPanelLienzo();
        lienzo.setBackground(new Color(GenerateRand(), GenerateRand(), GenerateRand()));
        
        ventana.add(menu, BorderLayout.NORTH);
        ventana.add(lienzo, BorderLayout.CENTER);
        
        ventana.setDefaultCloseOperation(EXIT_ON_CLOSE);
        ventana.setVisible(true);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
