/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Fer
 */
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Toolkit;

public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        Menu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        NuevoArchivo = new javax.swing.JMenuItem();
        AbrirArchivo = new javax.swing.JMenuItem();
        GuardarArchivo = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Salir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Copiar = new javax.swing.JMenuItem();
        Pegar = new javax.swing.JMenuItem();
        Deshacer = new javax.swing.JMenuItem();
        Rehacer = new javax.swing.JMenuItem();
        Vista = new javax.swing.JMenu();
        Vista100 = new javax.swing.JMenuItem();
        Vista75 = new javax.swing.JMenuItem();
        Vista50 = new javax.swing.JMenuItem();
        Vista25 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        AcercaDe = new javax.swing.JMenuItem();
        Creditos = new javax.swing.JMenuItem();
        Manual = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Archivo");

        NuevoArchivo.setText("Nuevo");
        NuevoArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoArchivoActionPerformed(evt);
            }
        });
        jMenu1.add(NuevoArchivo);

        AbrirArchivo.setText("Abrir");
        jMenu1.add(AbrirArchivo);

        GuardarArchivo.setText("Guardar");
        GuardarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarArchivoActionPerformed(evt);
            }
        });
        jMenu1.add(GuardarArchivo);
        jMenu1.add(jSeparator1);

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        jMenu1.add(Salir);

        Menu.add(jMenu1);

        jMenu2.setText("Edición");

        Copiar.setText("Copiar");
        jMenu2.add(Copiar);

        Pegar.setText("Pegar");
        jMenu2.add(Pegar);

        Deshacer.setText("Deshacer");
        jMenu2.add(Deshacer);

        Rehacer.setText("Rehacer");
        jMenu2.add(Rehacer);

        Vista.setText("Vista");

        Vista100.setText("100%");
        Vista100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Vista100ActionPerformed(evt);
            }
        });
        Vista.add(Vista100);

        Vista75.setText("75%");
        Vista75.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Vista75ActionPerformed(evt);
            }
        });
        Vista.add(Vista75);

        Vista50.setText("50%");
        Vista50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Vista50ActionPerformed(evt);
            }
        });
        Vista.add(Vista50);

        Vista25.setText("25%");
        Vista25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Vista25ActionPerformed(evt);
            }
        });
        Vista.add(Vista25);

        jMenu2.add(Vista);

        Menu.add(jMenu2);

        jMenu3.setText("Ayuda");

        AcercaDe.setText("Acerca de");
        jMenu3.add(AcercaDe);

        Creditos.setText("Créditos");
        Creditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreditosActionPerformed(evt);
            }
        });
        jMenu3.add(Creditos);

        Manual.setText("Manual");
        jMenu3.add(Manual);

        Menu.add(jMenu3);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NuevoArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NuevoArchivoActionPerformed

    private void GuardarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuardarArchivoActionPerformed

    private void CreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreditosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreditosActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void Vista100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Vista100ActionPerformed
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_Vista100ActionPerformed

    private void Vista75ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Vista75ActionPerformed
        this.setSize(((int) (Pantalla.width * 0.75)), ((int) (Pantalla.height * 0.75)));
    }//GEN-LAST:event_Vista75ActionPerformed

    private void Vista50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Vista50ActionPerformed
        this.setSize(((int) (Pantalla.width * 0.50)), ((int) (Pantalla.height * 0.50)));
    }//GEN-LAST:event_Vista50ActionPerformed

    private void Vista25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Vista25ActionPerformed
        this.setSize(((int) (Pantalla.width * 0.25)), ((int) (Pantalla.height * 0.25)));
    }//GEN-LAST:event_Vista25ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        MiVentana ventana = new MiVentana();
        ventana.setLayout(new BorderLayout());
        
        MiPanelMenu menu = new MiPanelMenu();
        menu.setBackground(new Color(20, 20, 20));
        
        MiPanelLienzo lienzo = new MiPanelLienzo();
        
        ventana.add(menu, BorderLayout.NORTH);
        ventana.add(lienzo, BorderLayout.CENTER);
        ventana.setDefaultCloseOperation(EXIT_ON_CLOSE);
        ventana.setVisible(true);
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }
    
    private java.awt.Dimension Pantalla = Toolkit.getDefaultToolkit().getScreenSize();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AbrirArchivo;
    private javax.swing.JMenuItem AcercaDe;
    private javax.swing.JMenuItem Copiar;
    private javax.swing.JMenuItem Creditos;
    private javax.swing.JMenuItem Deshacer;
    private javax.swing.JMenuItem GuardarArchivo;
    private javax.swing.JMenuItem Manual;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenuItem NuevoArchivo;
    private javax.swing.JMenuItem Pegar;
    private javax.swing.JMenuItem Rehacer;
    private javax.swing.JMenuItem Salir;
    private javax.swing.JMenu Vista;
    private javax.swing.JMenuItem Vista100;
    private javax.swing.JMenuItem Vista25;
    private javax.swing.JMenuItem Vista50;
    private javax.swing.JMenuItem Vista75;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
